// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvBWXvMi2Mskr1z1gJ8Vm3FWW414f_GRc',
    appId: '1:418594615286:web:563b7bb1965d948f8821d7',
    messagingSenderId: '418594615286',
    projectId: 'cinemapro2710',
    authDomain: 'cinemapro2710.firebaseapp.com',
    databaseURL: 'https://cinemapro2710-default-rtdb.firebaseio.com',
    storageBucket: 'cinemapro2710.firebasestorage.app',
    measurementId: 'G-DWDHYY1PCM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3pXx_-3l1PsuL-J2ypNZTo-i4zBnka1o',
    appId: '1:418594615286:android:9e3bec6bd79ea6568821d7',
    messagingSenderId: '418594615286',
    projectId: 'cinemapro2710',
    databaseURL: 'https://cinemapro2710-default-rtdb.firebaseio.com',
    storageBucket: 'cinemapro2710.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvBWXvMi2Mskr1z1gJ8Vm3FWW414f_GRc',
    appId: '1:418594615286:web:936874307928d0488821d7',
    messagingSenderId: '418594615286',
    projectId: 'cinemapro2710',
    authDomain: 'cinemapro2710.firebaseapp.com',
    databaseURL: 'https://cinemapro2710-default-rtdb.firebaseio.com',
    storageBucket: 'cinemapro2710.firebasestorage.app',
    measurementId: 'G-2HW1DY36RY',
  );

}