#!/bin/sh
if [ -f STRIPE_PAYMENT_SETUP.md ]; then
    sed -i.bak 's/sk_test_51SkM1bF20g1EMWhN9IkmSiRMEHQJbM0HUr6nYa6vz7IXfbWHfmmROrw1mbzjivS3989mn3zNUKdan8Q6sbFGfRob00TkydFF7A/sk_test_YOUR_STRIPE_SECRET_KEY_HERE/g' STRIPE_PAYMENT_SETUP.md
    rm -f STRIPE_PAYMENT_SETUP.md.bak
fi
if [ -f GOOGLE_PAY_CONFIGURATION_COMPLETE.md ]; then
    sed -i.bak 's/sk_test_51SkM1bF20g1EMWhN9IkmSiRMEHQJbM0HUr6nYa6vz7IXfbWHfmmROrw1mbzjivS3989mn3zNUKdan8Q6sbFGfRob00TkydFF7A/sk_test_YOUR_STRIPE_SECRET_KEY_HERE/g' GOOGLE_PAY_CONFIGURATION_COMPLETE.md
    rm -f GOOGLE_PAY_CONFIGURATION_COMPLETE.md.bak
fi

